lebensbaum_contao_system_info:
    path: /_domainverwaltung/systeminfo
    controller: Lebensbaum\ContaoSystemInfoBundle\Controller\SystemInfoController
    methods: [GET]
    defaults:
        _format: json
        _bypass_maintenance: true

lebensbaum_contao_system_info_logs:
    path: /_domainverwaltung/logs
    controller: Lebensbaum\ContaoSystemInfoBundle\Controller\LogController
    methods: [GET]
    defaults:
        _format: json
        _bypass_maintenance: true

lebensbaum_contao_system_info_backup_create:
    path: /_domainverwaltung/actions/backup
    controller: Lebensbaum\ContaoSystemInfoBundle\Controller\BackupController::create
    methods: [POST]
    defaults:
        _format: json
        _bypass_maintenance: true

lebensbaum_contao_system_info_backup_list:
    path: /_domainverwaltung/actions/backups
    controller: Lebensbaum\ContaoSystemInfoBundle\Controller\BackupController::list
    methods: [GET]
    defaults:
        _format: json
        _bypass_maintenance: true

lebensbaum_contao_system_info_backup_restore:
    path: /_domainverwaltung/actions/restore
    controller: Lebensbaum\ContaoSystemInfoBundle\Controller\RestoreController::restore
    methods: [POST]
    defaults:
        _format: json
        _bypass_maintenance: true
